{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}
source:
  git_url: ../

package:
  name: dropbot-monitor
  version: {{ GIT_VERSION }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python

  run:
    - blinker
    - logging-helpers
    - paho-mqtt
    - python

test:
  imports:
    - dropbot_monitor

about:
  home: https://github.com/sci-bots/dropbot-monitor
  license: BSD

extra:
  recipe-maintainers:
    - cfobel
